import subprocess
import json
import os
import time

AGENTAPI_PATH = "/Users/vedat/.gemini/antigravity/bin/agentapi"

def generate_with_agentapi(prompt: str, model: str = "pro") -> str:
    """
    Calls the local pre-authorized Antigravity agentapi CLI tool
    to run text generation using the user's active paid subscription.
    """
    try:
        # Run command to start a new conversation
        process = subprocess.run(
            [AGENTAPI_PATH, "new-conversation", f"--model={model}", prompt],
            capture_output=True,
            text=True,
            timeout=30
        )
        if process.returncode != 0:
            raise Exception(f"agentapi execution failed: {process.stderr.strip() or process.stdout.strip()}")
            
        data = json.loads(process.stdout.strip())
        conversation_id = data["response"]["newConversation"]["conversationId"]
        
        # Path to the transcript log
        log_path = f"/Users/vedat/.gemini/antigravity/brain/{conversation_id}/.system_generated/logs/transcript.jsonl"
        
        # Wait up to 10 seconds for the backend language_server to flush the response to the file
        attempts = 0
        while not os.path.exists(log_path) and attempts < 20:
            time.sleep(0.5)
            attempts += 1
            
        if not os.path.exists(log_path):
            raise Exception("Timeout waiting for transcript log to be generated by language_server")
            
        # Parse the JSONL to extract the model's response
        time.sleep(0.2) # small buffer to make sure write is finished
        with open(log_path, 'r', encoding='utf-8') as f:
            for line in f:
                if not line.strip():
                    continue
                step = json.loads(line)
                if step.get("source") == "MODEL" and step.get("type") == "PLANNER_RESPONSE":
                    return step.get("content", "").strip()
                    
        raise Exception("Model response block not found in conversation transcript")
        
    except Exception as e:
        # Fallback to a clean error description
        return f"Error using local Antigravity engine: {str(e)}"
